dsimmon1/theInventory

- public/inventory-view-all.html
- public/js/inventory-view-all.js
@vmov031 Here's the html and some of the js for the inventory display. I wanted to dynamically generate the columns names, too. I'll try to do that later.
> inventory html and js

- public/js/dashboard.js
- routes/dashboard-routes.js
- views/header.ejs
> [changes for the dashboard changes for d3]

- app.js
- routes/user.js
- views/sidebar.ejs
> inventory ejs page

- schema.sql
@mateyo3 updating schema for sequelize
> commenting schema

- app.js
> updating app server

- public/404.html
- public/js/inventory-view-all.js
- routes/html-routes.js
> updates to routes/inventory

- public/js/chart2.js
- public/js/dashboard.js
- routes/api-routes.js
- server.js
- views/dashboard.ejs
- views/header.ejs
added the first chart to the dashboard and more to the route api
> changes for the charts for the dashboard.

- public/js/orders.js
@dsimmon1 @jandeguzman @mateyo3 @shararsh
> updating orders js

- views/inventory.ejs
- views/orders.ejs
- views/stockcontrol.ejs
@shararsh @dsimmon1 @mateyo3 @vmov031
> stock control, order, inventory layout

- views/dashboard.ejs
- views/header.ejs
> fix the layout header

- app.js
- views/signup.ejs
> fix mobile number field

- app.js
> removed mateyo password

- app.js
> sessions fix to 120000000

- public/js/chart2.js
- public/js/chart3.js
- views/dashboard.ejs
> [added the chart 1 and 2 with dummy data]

- app.js
- models/user.js
- views/inventory.ejs
> updating app js with some server elements

- public/js/total.js
- routes/api-routes.js
- views/header.ejs
> [adds the total inventory]

- app.js
- public/js/stockcontrol.js
- routes/stockcontrol-routes.js
- seed-inventory.sql
- views/stockcontrol.ejs
> stock transfer

- app.js
> api route thing

- views/inventory.ejs
- views/stockcontrol.ejs
> stock control and inventory header

- views/header.ejs
> dashboard charts

- models/history.js
- public/js/chart3.js
- seed-inventory.sql
- views/dashboard.ejs
- views/header.ejs
> changes to the seed and order history and dashboard

- config/config.json
- public/js/inventory-view-all.js
- seed-users.sql
- views/header.ejs
- views/index.ejs
- views/inventory.ejs
Some columns were showing "null" because we didn't have those in the MySQL table anymore. I removed them from the inventory.ejs and inventory-view-all.js files.
I also changed the title in the head and removed the "create account" on the log in page
> Inventory changes

- views/index.ejs
> uncommented create user

- public/js/chart1.js
- public/js/chart2.js
- routes/api-routes.js
> final changes for dashboard

- views/header.ejs
> warehouse 1
